version: "3"
services:
  react:
    build:
      context: ./react_app
    volumes:
      - ./react_app:/app
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend/site
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    build:
      context: ./backend/bot
    environment:
      TG_TOKEN: ${TG_TOKEN}
    volumes:
      - ./backend/bot:/app
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build:
      context: ./backend/db
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./backend/nginx
