version: "3"
services:
  react:
    build:
      context: ./react_app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./site_backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  bot:
    build:
      context: ./bot
    environment:
      TOKEN: ${TG_TOKEN}
    volumes:
      - ./:/app
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build:
      context: ./db
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
